<?php  //[STAMP] 705f3a32e302ea321c0eaf6bedec0cbd
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Helper\ListClients;

trait ListClientsTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
